version: "3.7"
services:
  
  lucifer:
    image: postgres:latest
    container_name: lucifer
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: RobotBoy
      POSTGRES_PASSWORD: RobotBoy  # To be moved to environment file
      POSTGRES_DATABASE: Lucifer
    volumes:
      - ./postgres/lucifer:/var/lib/postgresql/lucifer

  kharonte:
    image: postgres:latest
    container_name: kharonte
    restart: always
    ports:
      - 5433:5432
    expose:
      - 5433
    environment:
      POSTGRES_USER: RobotBoy
      POSTGRES_PASSWORD: RobotBoy  # To be moved to environment file
      POSTGRES_DATABASE: Kharonte
    volumes:
      - ./postgres/kharonte:/var/lib/postgresql/kharonte

  zoo1:
    image: zookeeper:latest
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk/zoo1/data:/data
      - ./zk/zoo1/datalog:/datalog

  kafka1:
      image: confluentinc/cp-kafka:latest
      container_name: kafka1
      restart: always
      hostname: kafka1
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
        KAFKA_BROKER_ID: 1
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      volumes:
        - ./kafka/kafka1/data:/var/lib/kafka/data
      depends_on:
        - zoo1
  seq:
      image: datalust/seq:latest
      container_name: seq
      restart: always
      ports:
        - 5341:5341
      expose:
        - 5341
      environment:
        ACCEPT_EULA: Y
      volumes:
        - ./seq/data:/data
